version: '3'

services:
  
  todotests:
    # image: todotests
    build: ./todo-app/tests/
    restart: always
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
  
  todofront:
    # image: todofrontend
    build: ./todo-app/front-end/
    restart: always
    ports:
      -3000:3000
    depends_on:
      - "todoback"
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
  
  todoback:
    # image: todobackend
    build: ./todo-app/back-end/
    restart: always
    ports:
      - 3001:3001